export const courses = [
    {
        id: 1,
        name: "Giao tiếp cơ bản",
        imageSrc:
            "https://www.ieltsasia.org/vn/sites/www.ieltsasia.org.vn/files/ielts-registration-39516.jpg",
        imageAlt: "Front of men's Basic Tee in black.",
        price: 1250000,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, assumenda! Reprehenderit laboriosam aut a molestiae possimus ex, perferendis tempore iure, facilis, impedit hic dicta nam vero quibusdam. Dolore, veritatis quia!",
        highlights: [
            "Đào tạo từ cơ bản đến nâng cao",
            "Giáo trình đầy đủ",
            "Thời gian đào tạo không quá dài",
            "Có đầy đủ các bài kiểm tra kỹ năng",
        ],
        startAt: "20/10/2022",
        studentNumber: "40",
        trainingTime: "60",
        lessonPerWeek: "3",
        entity: "Sinh viên",
        showInLanding: true,
    },
    {
        id: 2,
        name: "Đọc viết cơ bản",
        imageSrc:
            "https://www.ieltsasia.org/vn/sites/www.ieltsasia.org.vn/files/ielts-registration-39516.jpg",
        imageAlt: "Front of men's Basic Tee in black.",
        price: 1550000,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, assumenda! Reprehenderit laboriosam aut a molestiae possimus ex, perferendis tempore iure, facilis, impedit hic dicta nam vero quibusdam. Dolore, veritatis quia!",
        highlights: [
            "Đào tạo từ cơ bản đến nâng cao",
            "Giáo trình đầy đủ",
            "Thời gian đào tạo không quá dài",
            "Có đầy đủ các bài kiểm tra kỹ năng",
        ],
        startAt: "20/10/2022",
        studentNumber: "40",
        trainingTime: "60",
        lessonPerWeek: "3",
        entity: "Sinh viên",
        showInLanding: true,
    },
    {
        id: 3,
        name: "Giao tiếp nâng cao",
        imageSrc:
            "https://www.ieltsasia.org/vn/sites/www.ieltsasia.org.vn/files/ielts-registration-39516.jpg",
        imageAlt: "Front of men's Basic Tee in black.",
        price: 1250000,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, assumenda! Reprehenderit laboriosam aut a molestiae possimus ex, perferendis tempore iure, facilis, impedit hic dicta nam vero quibusdam. Dolore, veritatis quia!",
        highlights: [
            "Đào tạo từ cơ bản đến nâng cao",
            "Giáo trình đầy đủ",
            "Thời gian đào tạo không quá dài",
            "Có đầy đủ các bài kiểm tra kỹ năng",
        ],
        startAt: "20/10/2022",
        studentNumber: "40",
        trainingTime: "60",
        lessonPerWeek: "3",
        entity: "Sinh viên",
        showInLanding: false,
    },
    {
        id: 4,
        name: "Đọc viết nâng cao",
        imageSrc:
            "https://www.ieltsasia.org/vn/sites/www.ieltsasia.org.vn/files/ielts-registration-39516.jpg",
        imageAlt: "Front of men's Basic Tee in black.",
        price: 1350000,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, assumenda! Reprehenderit laboriosam aut a molestiae possimus ex, perferendis tempore iure, facilis, impedit hic dicta nam vero quibusdam. Dolore, veritatis quia!",
        highlights: [
            "Đào tạo từ cơ bản đến nâng cao",
            "Giáo trình đầy đủ",
            "Thời gian đào tạo không quá dài",
            "Có đầy đủ các bài kiểm tra kỹ năng",
        ],
        startAt: "20/10/2022",
        studentNumber: "40",
        trainingTime: "60",
        lessonPerWeek: "3",
        entity: "Sinh viên",
        showInLanding: true,
    },
    {
        id: 5,
        name: "Chứng chỉ TOEIC",
        imageSrc:
            "https://www.ieltsasia.org/vn/sites/www.ieltsasia.org.vn/files/ielts-registration-39516.jpg",
        imageAlt: "Front of men's Basic Tee in black.",
        price: 1500000,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, assumenda! Reprehenderit laboriosam aut a molestiae possimus ex, perferendis tempore iure, facilis, impedit hic dicta nam vero quibusdam. Dolore, veritatis quia!",
        highlights: [
            "Đào tạo từ cơ bản đến nâng cao",
            "Giáo trình đầy đủ",
            "Thời gian đào tạo không quá dài",
            "Có đầy đủ các bài kiểm tra kỹ năng",
        ],
        startAt: "20/10/2022",
        studentNumber: "40",
        trainingTime: "60",
        lessonPerWeek: "3",
        entity: "Sinh viên",
        showInLanding: false,
    },
    {
        id: 6,
        name: "Chứng chỉ B2",
        imageSrc:
            "https://www.ieltsasia.org/vn/sites/www.ieltsasia.org.vn/files/ielts-registration-39516.jpg",
        imageAlt: "Front of men's Basic Tee in black.",
        price: 1250000,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, assumenda! Reprehenderit laboriosam aut a molestiae possimus ex, perferendis tempore iure, facilis, impedit hic dicta nam vero quibusdam. Dolore, veritatis quia!",
        highlights: [
            "Đào tạo từ cơ bản đến nâng cao",
            "Giáo trình đầy đủ",
            "Thời gian đào tạo không quá dài",
            "Có đầy đủ các bài kiểm tra kỹ năng",
        ],
        startAt: "20/10/2022",
        studentNumber: "40",
        trainingTime: "60",
        lessonPerWeek: "3",
        entity: "Sinh viên",
        showInLanding: false,
    },
    {
        id: 7,
        name: "Chứng chỉ B1",
        imageSrc:
            "https://www.ieltsasia.org/vn/sites/www.ieltsasia.org.vn/files/ielts-registration-39516.jpg",
        imageAlt: "Front of men's Basic Tee in black.",
        price: 1350000,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, assumenda! Reprehenderit laboriosam aut a molestiae possimus ex, perferendis tempore iure, facilis, impedit hic dicta nam vero quibusdam. Dolore, veritatis quia!",
        highlights: [
            "Đào tạo từ cơ bản đến nâng cao",
            "Giáo trình đầy đủ",
            "Thời gian đào tạo không quá dài",
            "Có đầy đủ các bài kiểm tra kỹ năng",
        ],
        startAt: "20/10/2022",
        studentNumber: "40",
        trainingTime: "60",
        lessonPerWeek: "3",
        entity: "Sinh viên",
        showInLanding: false,
    },
    // More products...
];
