export const courses = [
    {
        id: 1,
        name: "Giao tiếp cơ bản",
        imageSrc:
            "https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-04.jpg",
        imageAlt: "Front of men's Basic Tee in black.",
        price: "$35",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, assumenda! Reprehenderit laboriosam aut a molestiae possimus ex, perferendis tempore iure, facilis, impedit hic dicta nam vero quibusdam. Dolore, veritatis quia!",
        highlights: [
            "Đào tạo từ cơ bản đến nâng cao",
            "Giáo trình đầy đủ",
            "Thời gian đào tạo không quá dài",
            "Có đầy đủ các bài kiểm tra kỹ năng",
        ],
        startAt: "20/10/2022",
        studentNumber: "40",
        trainingTime: "60",
        lessonPerWeek: "3",
        entity: "Sinh viên",
    },
    {
        id: 2,
        name: "Đọc viết cơ bản",
        imageSrc:
            "https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-02.jpg",
        imageAlt: "Front of men's Basic Tee in black.",
        price: "$35",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, assumenda! Reprehenderit laboriosam aut a molestiae possimus ex, perferendis tempore iure, facilis, impedit hic dicta nam vero quibusdam. Dolore, veritatis quia!",
        highlights: [
            "Đào tạo từ cơ bản đến nâng cao",
            "Giáo trình đầy đủ",
            "Thời gian đào tạo không quá dài",
            "Có đầy đủ các bài kiểm tra kỹ năng",
        ],
        startAt: "20/10/2022",
        studentNumber: "40",
        trainingTime: "60",
        lessonPerWeek: "3",
        entity: "Sinh viên",
    },
    {
        id: 3,
        name: "Giao tiếp nâng cao",
        imageSrc:
            "https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-04.jpg",
        imageAlt: "Front of men's Basic Tee in black.",
        price: "$35",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, assumenda! Reprehenderit laboriosam aut a molestiae possimus ex, perferendis tempore iure, facilis, impedit hic dicta nam vero quibusdam. Dolore, veritatis quia!",
        highlights: [
            "Đào tạo từ cơ bản đến nâng cao",
            "Giáo trình đầy đủ",
            "Thời gian đào tạo không quá dài",
            "Có đầy đủ các bài kiểm tra kỹ năng",
        ],
        startAt: "20/10/2022",
        studentNumber: "40",
        trainingTime: "60",
        lessonPerWeek: "3",
        entity: "Sinh viên",
    },
    {
        id: 4,
        name: "Đọc viết nâng cao",
        imageSrc:
            "https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-03.jpg",
        imageAlt: "Front of men's Basic Tee in black.",
        price: "$35",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, assumenda! Reprehenderit laboriosam aut a molestiae possimus ex, perferendis tempore iure, facilis, impedit hic dicta nam vero quibusdam. Dolore, veritatis quia!",
        highlights: [
            "Đào tạo từ cơ bản đến nâng cao",
            "Giáo trình đầy đủ",
            "Thời gian đào tạo không quá dài",
            "Có đầy đủ các bài kiểm tra kỹ năng",
        ],
        startAt: "20/10/2022",
        studentNumber: "40",
        trainingTime: "60",
        lessonPerWeek: "3",
        entity: "Sinh viên",
    },
    {
        id: 5,
        name: "Chứng chỉ TOEIC",
        imageSrc:
            "https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-04.jpg",
        imageAlt: "Front of men's Basic Tee in black.",
        price: "$35",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, assumenda! Reprehenderit laboriosam aut a molestiae possimus ex, perferendis tempore iure, facilis, impedit hic dicta nam vero quibusdam. Dolore, veritatis quia!",
        highlights: [
            "Đào tạo từ cơ bản đến nâng cao",
            "Giáo trình đầy đủ",
            "Thời gian đào tạo không quá dài",
            "Có đầy đủ các bài kiểm tra kỹ năng",
        ],
        startAt: "20/10/2022",
        studentNumber: "40",
        trainingTime: "60",
        lessonPerWeek: "3",
        entity: "Sinh viên",
    },
    {
        id: 6,
        name: "Chứng chỉ B2",
        imageSrc:
            "https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-04.jpg",
        imageAlt: "Front of men's Basic Tee in black.",
        price: "$35",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, assumenda! Reprehenderit laboriosam aut a molestiae possimus ex, perferendis tempore iure, facilis, impedit hic dicta nam vero quibusdam. Dolore, veritatis quia!",
        highlights: [
            "Đào tạo từ cơ bản đến nâng cao",
            "Giáo trình đầy đủ",
            "Thời gian đào tạo không quá dài",
            "Có đầy đủ các bài kiểm tra kỹ năng",
        ],
        startAt: "20/10/2022",
        studentNumber: "40",
        trainingTime: "60",
        lessonPerWeek: "3",
        entity: "Sinh viên",
    },
    {
        id: 7,
        name: "Chứng chỉ B1",
        imageSrc:
            "https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-04.jpg",
        imageAlt: "Front of men's Basic Tee in black.",
        price: "$35",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, assumenda! Reprehenderit laboriosam aut a molestiae possimus ex, perferendis tempore iure, facilis, impedit hic dicta nam vero quibusdam. Dolore, veritatis quia!",
        highlights: [
            "Đào tạo từ cơ bản đến nâng cao",
            "Giáo trình đầy đủ",
            "Thời gian đào tạo không quá dài",
            "Có đầy đủ các bài kiểm tra kỹ năng",
        ],
        startAt: "20/10/2022",
        studentNumber: "40",
        trainingTime: "60",
        lessonPerWeek: "3",
        entity: "Sinh viên",
    },
    // More products...
];
