export const urls = {
    "*": "Tổng quan",
    "manage-staff": "Quản lý nhân viên",
    user: "Quản lý người dùng",
    "manage-home-page": "Quản lý trang chủ",
    "yeu-cau-lien-he": "Yêu cầu liên hệ",
    "manage-teacher": "Quản lý giáo viên",
    "manage-student": "Quản lý học viên",
    "manage-course": "Quản lý khóa học",
    "manage-category": "Quản lý loại hàng",
    "manage-product": "Quản lý sản phẩm",
    "manage-order": "Quản lý đơn hàng",
    tools: "Công cụ",
    statistical: "Thống kê",
};
